version: '3.4'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.0
    ports:
      - "8089:8080"
    restart: always
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
    - "keycloak_home:/opt/jboss/keycloak"
volumes:
  keycloak_home: {}