# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: DEBUG

# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000