# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: INFO


# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 6311390400000

# Properties parameter
dd-properties:
  status:
    1: "ACTIVE"
    2: "DRAFT"
    3: "DELIST"
  sold:
    1: "NO"
    2: "YES"
  tenure:
    1: "F"
    2: "L"
  features:
    "Penthouse": "PENT"
    "Cornerunit": "CORN"
    "Sea view": "SEAV"
    "City view": "CITYV"
    "Park/greenery view": "GREEN"
    "Swimming pool view": "POOLV"
    "Renovated": "RENO"
    "Original condition": "ORIG"
    "Ground floor": "GFLO"
    "Low floor": "LFLO"
    "High floor": "HFLO"
    "Colonial building": "COLO"
    "Meeting room": "MEET"
    "Video conference": "VCON"
    "ISDN internet": "ISDN"
    "Receptionist": "RECS"
    "High speed internet": "BROA"
    "Secretary": "SECR"
    "Contactor rest room": "RROOM"
    "AV equipment": "AVC"
    "CAT 5 cable wire": "CAT"
    "Air conditioning": "AIRC"
    "Bathtub": "BATH"
    "Cooker hob/hood": "COOK"
    "Hairdryer": "HAIR"
    "Intercom": "INT"
    "Jacuzzi": "JACZ"
    "Private pool": "PPOOL"
    "Water heater": "WHEAT"
    "IT support": "ITSUP"
    "Car park": "CARP"
    "Drinks provided": "WATER"
    "Free column": "CFREE"
    "Loading bay": "LBAY"
    "Pantry": "PANTR"
    "Kitchen": "KITCH"
  furnishing:
    1: "UNFUR"
    2: "PART"
    3: "FULL"
  facing:
    1: "NORTH"
    2: "NEAST"
    3: "NWEST"
    4: "EAST"
    5: "WEST"
    6: "SEAST"
    7: "SWEST"
    8: "SOUTH"
  amenities:
    "24hourssecurity": "SEC"
    "Badmintonhall": "BAD"
    "Basementcarpark": "BCAR"
    "Basketballcourt": "BAS"
    "BBQpits": "BBQ"
    "Billiardsroom": "BILL"
    "Clubhouse": "CLUB"
    "Coveredcarpark": "CCAR"
    "Drivingrange": "DRIV"
    "Fitnesscorner": "FIT"
    "Functionroom": "FUNC"
    "Gameroom": "GAME"
    "Gymnasiumroom": "GYM"
    "JacuzziKARKaraoke": "JAC"
    "Launderette": "LAU"
    "Library": "LIB"
    "Lounge": "LOU"
    "Minigolfrange": "MGOL"
    "Minimart": "MMAR"
    "Multipurposehall": "MULTI"
    "Opencarpark": "OCAR"
    "Playground": "PLAY"
    "Puttinggreen": "PUT"
    "ReflexologyPath": "REF"
    "Sauna": "SAUNA"
    "Spapool": "SPA"
    "Squashcourt": "SQU"
    "Steambath": "STE"
    "Swimmingpool": "SWI"
    "Tenniscourts": "TEN"
    "Wadingpool": "WAD"
    "Pooldeck": "PDEC"
    "Pavilion": "PAVI"
    "Skylounge": "SKYL"
    "Club": "CLB"
    "CCTV": "CTV"

# Aws Properties
aws:
  access-key: AKIAJ4BCHLWN6QAQPR5A
  secret-key: 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
  bucket-name: property-s3
  url: https://${aws.bucket-name}.s3-ap-southeast-1.amazonaws.com/

