# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: INFO

# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

# Aws Properties
aws:
  access-key: AKIAJ4BCHLWN6QAQPR5A
  secret-key: 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
  bucket-name: property-s3
  url: https://${aws.bucket-name}.s3-ap-southeast-1.amazonaws.com/

# Class name show calendar map
action-log-calendar:
  type-map-event-color:
    1: '#F0F8FF'
    2: '#FAEBD7'
    3: '#7FFFD4'
    4: '#FFF0F5'
    5: '#B8860B'
    6: '#E9967A'
    7: '#00BFFF'
    8: '#5F9EA0'
    9: '#A9A9A9'

# Pdf default parameter
pdf-default-parameters:
  default-value: "..............."
  lease-agreement:
    title1: ${pdf-default-parameters.default-value}
    title2: ${pdf-default-parameters.default-value}
    lessor: ${pdf-default-parameters.default-value}
    lessee: ${pdf-default-parameters.default-value}
    wintss1: ${pdf-default-parameters.default-value}
    wintss2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    idCardNumber: ${pdf-default-parameters.default-value}
    age: ${pdf-default-parameters.default-value}
    address: ${pdf-default-parameters.default-value}
    village: ${pdf-default-parameters.default-value}
    road: ${pdf-default-parameters.default-value}
    amphoe: ${pdf-default-parameters.default-value}
    district: ${pdf-default-parameters.default-value}
    province: ${pdf-default-parameters.default-value}
    and: ${pdf-default-parameters.default-value}
    idCardNuber2: ${pdf-default-parameters.default-value}
    age2: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    village2: ${pdf-default-parameters.default-value}
    road2: ${pdf-default-parameters.default-value}
    amphoe2: ${pdf-default-parameters.default-value}
    district2: ${pdf-default-parameters.default-value}
    province2: ${pdf-default-parameters.default-value}
    onwer: ${pdf-default-parameters.default-value}
    room: ${pdf-default-parameters.default-value}
    building: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    addressFull: ${pdf-default-parameters.default-value}
    rangeMonth: ${pdf-default-parameters.default-value}
    rangeDateStart: ${pdf-default-parameters.default-value}
    rangeDateEnd: ${pdf-default-parameters.default-value}
    monthlyRent: ${pdf-default-parameters.default-value}
    accountBank: ${pdf-default-parameters.default-value}
    accountName: ${pdf-default-parameters.default-value}
    accountNumber: ${pdf-default-parameters.default-value}
    monthlyRentPayAdvance: ${pdf-default-parameters.default-value}
    monthlyRentPayAll: ${pdf-default-parameters.default-value}
  realEstateAgentAgreement:
    seller: ${pdf-default-parameters.default-value}
    agent: ${pdf-default-parameters.default-value}
    wintss1: ${pdf-default-parameters.default-value}
    wintss2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    dateTinme: ${pdf-default-parameters.default-value}
    name: ${pdf-default-parameters.default-value}
    idCardNumberSale: ${pdf-default-parameters.default-value}
    addressSale: ${pdf-default-parameters.default-value}
    broker: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    building: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    addressFull: ${pdf-default-parameters.default-value}
    saleName: ${pdf-default-parameters.default-value}
    rangeDateStart: ${pdf-default-parameters.default-value}
    rangeDateEnd: ${pdf-default-parameters.default-value}