# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: INFO

# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 6311390400000

# Aws Properties
aws:
  access-key: AKIAJ4BCHLWN6QAQPR5A
  secret-key: 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
  bucket-name: property-s3
  url: https://${aws.bucket-name}.s3-ap-southeast-1.amazonaws.com/

# Class name show calendar map
action-log-calendar:
  type-map-event-color:
    1: '#F0F8FF'
    2: '#FAEBD7'
    3: '#7FFFD4'
    4: '#FFF0F5'
    5: '#B8860B'
    6: '#E9967A'
    7: '#00BFFF'
    8: '#5F9EA0'
    9: '#A9A9A9'

# Properties parameter
dd-properties:
  status:
    1: "ACTIVE"
    2: "DRAFT"
    3: "DELIST"
  sold:
    1: "NO"
    2: "YES"
  tenure:
    1: "F"
    2: "L"
  features:
    "Penthouse": "PENT"
    "Cornerunit": "CORN"
    "Sea view": "SEAV"
    "City view": "CITYV"
    "Park/greenery view": "GREEN"
    "Swimming pool view": "POOLV"
    "Renovated": "RENO"
    "Original condition": "ORIG"
    "Ground floor": "GFLO"
    "Low floor": "LFLO"
    "High floor": "HFLO"
    "Colonial building": "COLO"
    "Meeting room": "MEET"
    "Video conference": "VCON"
    "ISDN internet": "ISDN"
    "Receptionist": "RECS"
    "High speed internet": "BROA"
    "Secretary": "SECR"
    "Contactor rest room": "RROOM"
    "AV equipment": "AVC"
    "CAT 5 cable wire": "CAT"
    "Air conditioning": "AIRC"
    "Bathtub": "BATH"
    "Cooker hob/hood": "COOK"
    "Hairdryer": "HAIR"
    "Intercom": "INT"
    "Jacuzzi": "JACZ"
    "Private pool": "PPOOL"
    "Water heater": "WHEAT"
    "IT support": "ITSUP"
    "Car park": "CARP"
    "Drinks provided": "WATER"
    "Free column": "CFREE"
    "Loading bay": "LBAY"
    "Pantry": "PANTR"
    "Kitchen": "KITCH"
  furnishing:
    1: "UNFUR"
    2: "PART"
    3: "FULL"
  facing:
    1: "NORTH"
    2: "NEAST"
    3: "NWEST"
    4: "EAST"
    5: "WEST"
    6: "SEAST"
    7: "SWEST"
    8: "SOUTH"
  amenities:
    "24hourssecurity": "SEC"
    "Badmintonhall": "BAD"
    "Basementcarpark": "BCAR"
    "Basketballcourt": "BAS"
    "BBQpits": "BBQ"
    "Billiardsroom": "BILL"
    "Clubhouse": "CLUB"
    "Coveredcarpark": "CCAR"
    "Drivingrange": "DRIV"
    "Fitnesscorner": "FIT"
    "Functionroom": "FUNC"
    "Gameroom": "GAME"
    "Gymnasiumroom": "GYM"
    "JacuzziKARKaraoke": "JAC"
    "Launderette": "LAU"
    "Library": "LIB"
    "Lounge": "LOU"
    "Minigolfrange": "MGOL"
    "Minimart": "MMAR"
    "Multipurposehall": "MULTI"
    "Opencarpark": "OCAR"
    "Playground": "PLAY"
    "Puttinggreen": "PUT"
    "ReflexologyPath": "REF"
    "Sauna": "SAUNA"
    "Spapool": "SPA"
    "Squashcourt": "SQU"
    "Steambath": "STE"
    "Swimmingpool": "SWI"
    "Tenniscourts": "TEN"
    "Wadingpool": "WAD"
    "Pooldeck": "PDEC"
    "Pavilion": "PAVI"
    "Skylounge": "SKYL"
    "Club": "CLB"
    "CCTV": "CTV"

# Pdf default parameter
pdf-default-parameters:
  default-value: "..............."
  lease-agreement:
    title1: ${pdf-default-parameters.default-value}
    title2: ${pdf-default-parameters.default-value}
    lessor: ${pdf-default-parameters.default-value}
    lessee: ${pdf-default-parameters.default-value}
    wintss1: ${pdf-default-parameters.default-value}
    wintss2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    idCardNumber: ${pdf-default-parameters.default-value}
    age: ${pdf-default-parameters.default-value}
    address: ${pdf-default-parameters.default-value}
    village: ${pdf-default-parameters.default-value}
    road: ${pdf-default-parameters.default-value}
    amphoe: ${pdf-default-parameters.default-value}
    district: ${pdf-default-parameters.default-value}
    province: ${pdf-default-parameters.default-value}
    and: ${pdf-default-parameters.default-value}
    idCardNumber2: ${pdf-default-parameters.default-value}
    age2: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    village2: ${pdf-default-parameters.default-value}
    road2: ${pdf-default-parameters.default-value}
    amphoe2: ${pdf-default-parameters.default-value}
    district2: ${pdf-default-parameters.default-value}
    province2: ${pdf-default-parameters.default-value}
    owner: ${pdf-default-parameters.default-value}
    room: ${pdf-default-parameters.default-value}
    building: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    addressFull: ${pdf-default-parameters.default-value}
    rangeMonth: ${pdf-default-parameters.default-value}
    rangeDateStart: ${pdf-default-parameters.default-value}
    rangeDateEnd: ${pdf-default-parameters.default-value}
    monthlyRent: ${pdf-default-parameters.default-value}
    accountBank: ${pdf-default-parameters.default-value}
    accountName: ${pdf-default-parameters.default-value}
    accountNumber: ${pdf-default-parameters.default-value}
    monthlyRentPayAdvance: ${pdf-default-parameters.default-value}
    monthlyRentPayAll: ${pdf-default-parameters.default-value}
  realEstateAgentAgreement:
    seller: ${pdf-default-parameters.default-value}
    agent: ${pdf-default-parameters.default-value}
    wintss1: ${pdf-default-parameters.default-value}
    wintss2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    dateTinme: ${pdf-default-parameters.default-value}
    name: ${pdf-default-parameters.default-value}
    idCardNumberSale: ${pdf-default-parameters.default-value}
    addressSale: ${pdf-default-parameters.default-value}
    broker: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    building: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    addressFull: ${pdf-default-parameters.default-value}
    saleName: ${pdf-default-parameters.default-value}
    rangeDateStart: ${pdf-default-parameters.default-value}
    rangeDateEnd: ${pdf-default-parameters.default-value}
  sellAndPurchaseAgreementEng:
    saller: ${pdf-default-parameters.default-value}
    buyer: ${pdf-default-parameters.default-value}
    witness: ${pdf-default-parameters.default-value}
    agent: ${pdf-default-parameters.default-value}
    titleYear1: ${pdf-default-parameters.default-value}
    titleYear2: ${pdf-default-parameters.default-value}
    title1: ${pdf-default-parameters.default-value}
    title2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    address1: ${pdf-default-parameters.default-value}
    idCardNumber1: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    idCardNumber2: ${pdf-default-parameters.default-value}
    roomName: ${pdf-default-parameters.default-value}
    roomNumber: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    width: ${pdf-default-parameters.default-value}
    long: ${pdf-default-parameters.default-value}
    height: ${pdf-default-parameters.default-value}
    address3: ${pdf-default-parameters.default-value}
    address4: ${pdf-default-parameters.default-value}
    road: ${pdf-default-parameters.default-value}
    amphoe: ${pdf-default-parameters.default-value}
    district: ${pdf-default-parameters.default-value}
    province: ${pdf-default-parameters.default-value}
    zipcode: ${pdf-default-parameters.default-value}
    price: ${pdf-default-parameters.default-value}
    contract2: ${pdf-default-parameters.default-value}
    price2: ${pdf-default-parameters.default-value}
    registry: ${pdf-default-parameters.default-value}
    dateRegistry: ${pdf-default-parameters.default-value}
    addNewRule: ${pdf-default-parameters.default-value}
    contract3: ${pdf-default-parameters.default-value}
    passport: ${pdf-default-parameters.default-value}
    premises: ${pdf-default-parameters.default-value}
    price3: ${pdf-default-parameters.default-value}
    price4: ${pdf-default-parameters.default-value}
    dateRegistry2: ${pdf-default-parameters.default-value}
    contractTH: ${pdf-default-parameters.default-value}
    address1TH: ${pdf-default-parameters.default-value}
    idCardNumber1TH: ${pdf-default-parameters.default-value}
    contract2TH: ${pdf-default-parameters.default-value}
    address2TH: ${pdf-default-parameters.default-value}
    idCardNumber2TH: ${pdf-default-parameters.default-value}
    contract3TH: ${pdf-default-parameters.default-value}
    passportTH: ${pdf-default-parameters.default-value}
    roomNameTH: ${pdf-default-parameters.default-value}
    roomNumberTH: ${pdf-default-parameters.default-value}
    floorTH: ${pdf-default-parameters.default-value}
    areaTH: ${pdf-default-parameters.default-value}
    widthTH: ${pdf-default-parameters.default-value}
    longTH: ${pdf-default-parameters.default-value}
    heightTH: ${pdf-default-parameters.default-value}
    premisesTH: ${pdf-default-parameters.default-value}
    priceTH: ${pdf-default-parameters.default-value}
    price2TH: ${pdf-default-parameters.default-value}
    price3TH: ${pdf-default-parameters.default-value}
    dateRegistryTH: ${pdf-default-parameters.default-value}
    price4TH: ${pdf-default-parameters.default-value}
    registryTH: ${pdf-default-parameters.default-value}
    dateRegistry2TH: ${pdf-default-parameters.default-value}
    tax: "0"
    addNewRuleTH: ${pdf-default-parameters.default-value}
  sellAndPurchaseAgreementTh:
    saller: ${pdf-default-parameters.default-value}
    buyer: ${pdf-default-parameters.default-value}
    witness: ${pdf-default-parameters.default-value}
    agent: ${pdf-default-parameters.default-value}
    title1: ${pdf-default-parameters.default-value}
    title2: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
    address1: ${pdf-default-parameters.default-value}
    idCardNumber1: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    idCardNumber2: ${pdf-default-parameters.default-value}
    roomName: ${pdf-default-parameters.default-value}
    roomNumber: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    width: ${pdf-default-parameters.default-value}
    long: ${pdf-default-parameters.default-value}
    height: ${pdf-default-parameters.default-value}
    address3: ${pdf-default-parameters.default-value}
    address4: ${pdf-default-parameters.default-value}
    road: ${pdf-default-parameters.default-value}
    amphoe: ${pdf-default-parameters.default-value}
    district: ${pdf-default-parameters.default-value}
    province: ${pdf-default-parameters.default-value}
    zipcode: ${pdf-default-parameters.default-value}
    price: ${pdf-default-parameters.default-value}
    contract2: ${pdf-default-parameters.default-value}
    price2: ${pdf-default-parameters.default-value}
    registry: ${pdf-default-parameters.default-value}
    dateRegistry: ${pdf-default-parameters.default-value}
    tax: "0"
    addNewRule: ${pdf-default-parameters.default-value}
  exclusiveAgreement:
    saller: ${pdf-default-parameters.default-value}
    buyer: ${pdf-default-parameters.default-value}
    witness: ${pdf-default-parameters.default-value}
    agent: ${pdf-default-parameters.default-value}
    title1: ${pdf-default-parameters.default-value}
    title2: ${pdf-default-parameters.default-value}
    name: ${pdf-default-parameters.default-value}
    idCardNumber: ${pdf-default-parameters.default-value}
    address: ${pdf-default-parameters.default-value}
    ownerName: ${pdf-default-parameters.default-value}
    roomNumber: ${pdf-default-parameters.default-value}
    floor: ${pdf-default-parameters.default-value}
    building: ${pdf-default-parameters.default-value}
    area: ${pdf-default-parameters.default-value}
    address2: ${pdf-default-parameters.default-value}
    reward: ${pdf-default-parameters.default-value}
    dateStart: ${pdf-default-parameters.default-value}
    dateEnd: ${pdf-default-parameters.default-value}
    contract: ${pdf-default-parameters.default-value}
  coBrokerFrom:
    coBrokeRef: ${pdf-default-parameters.default-value}
    enqRef: ${pdf-default-parameters.default-value}
    dateRegistration: ${pdf-default-parameters.default-value}
    companyName: ${pdf-default-parameters.default-value}
    representativeName: ${pdf-default-parameters.default-value}
    companyAddress: ${pdf-default-parameters.default-value}
    contact: ${pdf-default-parameters.default-value}
    title: ${pdf-default-parameters.default-value}
    name: ${pdf-default-parameters.default-value}
    surname: ${pdf-default-parameters.default-value}
    nationality: ${pdf-default-parameters.default-value}
    tel: ${pdf-default-parameters.default-value}
    email: ${pdf-default-parameters.default-value}
    checkboxTypeBuyClient: ${pdf-default-parameters.default-value}
    checkboxTypeRentClient: ${pdf-default-parameters.default-value}
    budget: ${pdf-default-parameters.default-value}
    bedroom: ${pdf-default-parameters.default-value}
    projectName: ${pdf-default-parameters.default-value}