# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: INFO

# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

# Aws Properties
aws:
  access-key: AKIAJ4BCHLWN6QAQPR5A
  secret-key: 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
  bucket-name: property-s3
  url: https://${aws.bucket-name}.s3-ap-southeast-1.amazonaws.com/

# Class name show calendar map
action-log-calendar:
  type-map-event-color:
    1: '#F0F8FF'
    2: '#FAEBD7'
    3: '#7FFFD4'
    4: '#FFF0F5'
    5: '#B8860B'
    6: '#E9967A'
    7: '#00BFFF'
    8: '#5F9EA0'
    9: '#A9A9A9'

# Pdf default parameter
pdf-default-parameters:
  lease-agreement:
    title1: ".........."
    title2: ".........."
    lessor: ".........."
    lessee: ".........."
    wintss1: ".........."
    wintss2: ".........."
    contract: ".........."
    idCardNumber: ".........."
    age: ".........."
    address: ".........."
    village: ".........."
    road: ".........."
    amphoe: ".........."
    district: ".........."
    province: ".........."
    and: ".........."
    idCardNuber2: ".........."
    age2: ".........."
    address2: ".........."
    village2: ".........."
    road2: ".........."
    amphoe2: ".........."
    district2: ".........."
    province2: ".........."
    onwer: ".........."
    room: ".........."
    building: ".........."
    floor: ".........."
    area: ".........."
    addressFull: ".........."
    rangeMonth: ".........."
    rangeDateStart: ".........."
    rangeDateEnd: ".........."
    monthlyRent: ".........."
    accountBank: ".........."
    accountName: ".........."
    accountNumber: ".........."
    monthlyRentPayAdvance: ".........."
    monthlyRentPayAll: ".........."
  realEstateAgentAgreement:
    seller: ".........."
    agent: ".........."
    wintss1: ".........."
    wintss2: ".........."