# Server Config
server:
  port : 8090

logging:
  level:
    ROOT: INFO


# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: p@ssw0rd


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

# Aws Properties
aws:
  access-key: AKIAJ4BCHLWN6QAQPR5A
  secret-key: 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
  bucket-name: property-s3
  url: https://${aws.bucket-name}.s3-ap-southeast-1.amazonaws.com/