# Server Config
server:
  port : 8090


# Mongo Db Config
spring:
  data:
    mongodb:
      database: property
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: password


# App Properties
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

# Aws Properties
aws:
  access-key: AKIAXCM6J3AOG6Y24WOE
  secret-key: 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
  bucket-name: property-s3